package fi.tuni.csgr.utils;
import fi.tuni.csgr.managers.graphs.BarGraphDataManager;
import javafx.scene.chart.XYChart;

import java.util.*;

public class StatfiAggregates extends BarGraphDataManager {
    /*
        This function will display the maximum value for the data which is generated by the series.
        The function fetches the data from the seriesData present in the GraphDataManager.
     */
    public double findMaximum(List<XYChart.Data<String, Double>> seriesData){
        Double result;
        List<Double> values = new ArrayList<>();
        for (int i=0; i< seriesData.size(); i++){
            result = (seriesData.get(i)).getYValue();

            values.add(result);
        }
        //System.out.println(values);
        double maximum = Collections.max(values);
        System.out.println("Maximum value of series data is "+maximum);
        return maximum;
    }
    /*
        This function will display the minimum value for the data which is generated by the series.
        The function fetches the data from the seriesData present in the GraphDataManager.
     */
    public double findMinimum(List<XYChart.Data<String, Double>> seriesData){
        Double result;
        List<Double> values = new ArrayList<>();
        for (int i=0; i< seriesData.size(); i++){
            result = (seriesData.get(i)).getYValue();

            values.add(result);
        }
        //System.out.println(values);
        double minimum = Collections.min(values);
        System.out.println("Minimum value of the series data is "+minimum);
        return minimum;
    }
    /*
        This function will display the Average value for the data which is generated by the series.
        The function fetches the data from the seriesData present in the GraphDataManager.
     */
    public double findAverage(List<XYChart.Data<String, Double>> seriesData){
        Double result;
        List<Double> values = new ArrayList<>();
        for (int i=0; i< seriesData.size(); i++){
            result = (seriesData.get(i)).getYValue();

            values.add(result);
        }
        double average = values.stream().mapToDouble(val -> val).average().orElse(0.0);
        System.out.println("Average value of the series data is "+average);
        return average;
    }
}
